### ISSUE TITLE
Feature request: autosave

### ISSUE THREAD

**Issue by de-ko** [nhydock/Storymode#19]
I'd like to have autosave feature implemented.
Let it use dedicated save slot and save every time character returns to the town.

**Comment by nhydock** [comment]
Feature added and will be pushed in a moment.  The autosave implementation saves to a new save slot instead of overwriting whatever slot you loaded from, so if you select the continue button it'll just have you create a new character until you start playing the game so it can autosave.  I feel this is safer than just loading whatever slot has the latest modified date, because if someone's system clock is messed up that could effect load order.
